# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-29 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='submit_date',
            new_name='submit',
        ),
    ]
